general:
  learning rate: 0.5
  epochs: 1000
  loss: binary cross entropy
  optimisation: stochastic gradient descent
  evaluation: classification
  activation: sigmoid
  initialisation: xavier normal
  batch size: 35
  

architecture: 
  input:
    size: 30
  hidden:
    count: 1
    size: [10]
  output:
    size: 1
    activation: sigmoid