general:
  learning rate: 0.05
  epochs: 5
  loss: mean square error
  optimisation: gradient descent

architecture: 
  input:
    size: 30
  hidden:
    count: 1
    size: [5]
    activation: sigmoid
    initializer: he Normal
  output:
    size: 1
    activation: sigmoid
    initializer: xavier Normal