general:
  learning rate: 0.5
  epochs: 1000
  loss: mean square error
  optimisation: gradient descent
  evaluation: classification
  activation: leaky relu
  initialisation: he normal

architecture: 
  input:
    size: 30
  hidden:
    count: 1
    size: [25]
  output:
    size: 1