general:
  learning rate: 0.75
  epochs: 100000
  loss: mean square error
  optimisation: gradient descent
  evaluation: classification

architecture: 
  input:
    size: 30
  hidden:
    count: 2
    size: [10,10]
    activation: sigmoid
    initializer: he Normal
  output:
    size: 1
    activation: sigmoid
    initializer: he Normal